pipeline {
    agent any

    environment {
        IMAGE_NAME = 'mern_frontend'
        IMAGE_TAG = 'latest'
        ECR_REPO = '629161160811.dkr.ecr.ap-south-1.amazonaws.com'
        NAMESPACE = 'mern-app'
        RELEASE_NAME = 'mern-frontend-release'
        CHART_PATH = 'frontend/mern-frontend-service'
        CLUSTER_NAME = 'mern-app-eks-cluster'
        AWS_REGION = 'ap-south-1'
    }

    stages {
        stage('Build Docker Image') {
            steps {
                dir('frontend') {
                    sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                }
            }
        }

        stage('Push to ECR') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-creds'
                ]]) {
                    sh '''
                    aws sts get-caller-identity
                    aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin ${ECR_REPO}
                    docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${ECR_REPO}/${IMAGE_NAME}:${IMAGE_TAG}
                    docker push ${ECR_REPO}/${IMAGE_NAME}:${IMAGE_TAG}
                    '''
                }
            }
        }

        stage('Configure EKS Access') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-creds'
                ]]) {
                    sh '''
                    aws eks update-kubeconfig --name ${CLUSTER_NAME} --region ${AWS_REGION}
                    kubectl get nodes
                    '''
                }
            }
        }

        stage('Deploy with Helm') {
            steps {
                sh '''
                helm install ${RELEASE_NAME} ${CHART_PATH} -n ${NAMESPACE} 
                
                '''
            }
        }
    }
}
