pipeline{

    agent any

    environment {
        IMAGE_NAME = "mern_frontend"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage ('Build Docker Image') {
            steps {
                dir('frontend') {
                    sh 'docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .'
                }
            }
        }

        stage ('Push Docker Image') {
            steps {
            
                withCredentials([
                    [
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'aws-creds']
                ]) 

                script {
                    sh 'aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 629161160811.dkr.ecr.ap-south-1.amazonaws.com'
                    sh 'docker tag ${IMAGE_NAME}:${IMAGE_TAG} 629161160811.dkr.ecr.ap-south-1.amazonaws.com/${IMAGE_NAME}:${IMAGE_TAG}'
                    sh 'docker push 629161160811.dkr.ecr.ap-south-1.amazonaws.com/${IMAGE_NAME}:${IMAGE_TAG}'
                }
            }
        }



    }
}
